services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: SHOw
      POSTGRES_PASSWORD: postSHO
      POSTGRES_DB: job_hunting_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: